### DISCUSSION TITLE
How to change the font of the code editor?

### DISCUSSION THREAD

**Discussion by HubKing** [openstyles/stylus#1330] [Q&A]
It seems to be using "Courier New" but that font sucks (too thin). How can I change the font to something else?

**Comment by tophf** [comment]
There are two methods:
1. change your global browser font in browser settings -> fonts -> monospace.
2. write a new userstyle that targets Stylus itself:

```css
@-moz-document url-prefix("chrome-extension://"), url-prefix("moz-extension://") {
  .CodeMirror { font-family: Consolas }
}
```
