### DISCUSSION TITLE
Codemirror's `bespin` theme has very bad selection highlight

### DISCUSSION THREAD

**Discussion by stdedos** [openstyles/stylus#1538] [General]
Hello there,

I am using the `bespin` theme for the CodeMirror editor. However, one very frustrating aspect of this, is that it has very bad visual feedback on selection

![image](https://user-images.githubusercontent.com/133706/215997631-2fbd79f5-ccb6-425c-8f70-d6b4419635d2.png)

I was wondering - is this something you'd consider changing locally?
Or should I ask upstream?

**Comment by tophf** [comment]
Looks like you may have another style that overrides the theme. You can either disable it or override it by making a new style:
```css
.cm-s-bespin div.CodeMirror-selected {background: #fff !important;}
```
