### DISCUSSION TITLE
Height of the popup

### DISCUSSION THREAD

**Discussion by Screenfeed** [openstyles/stylus#1588] [Ideas]
Hello,

I was wondering if it is possible to add a setting for the height (or min-height) of the popup, similarly to the width setting. The styles browser is so tiny.
I tried to use a `userChrome.css` file but the styles browser is not extended, only the popup itself x)
```css
#customizationui-widget-panel .webextension-popup-browser {
	height: 600px !important;
	min-height: 600px !important;
}
```

Thanks.

**Comment by tophf** [comment]
The browser should automatically extend the height. The maximum is 600px, which is a hardcoded limit in Chrome or Firefox. If you observe a bug with the height being much smaller than that please provide more info and a screenshot.

**Reply by Screenfeed** [reply]
I remember this popup being taller but not anymore.
This is the size it always is:
<img width="419" alt="image" src="https://user-images.githubusercontent.com/1878479/234023700-748e7d50-bb33-42e6-91fb-c04276e81c41.png">

Inspecting it, I see these dimensions applied to `.webextension-popup-browser` in a `style` tag:
```css
element {
    width: 402px;
    min-width: 402px;
    height: 267px;
    min-height: 267px;

}
```
