### DISCUSSION TITLE
Why do I get syntax errors when using LESS preprocessor?

### DISCUSSION THREAD

**Discussion by minnieoo** [openstyles/stylus#1711] [General]
i get these errors despite defining that i'm using less

```css
/* ==UserStyle==

@name           pinKbin
@namespace      github.com/openstyles/stylus
@version        1.0.1
@description    A few small visual improvements for kbin.
@author         minnie

@preprocessor less
==/UserStyle== */

:root {
    --white-PK: #fff8f8;
    --pink1-PK: #FFCEDF;
    --pink2-PK: #FF9CC8;
    --peach-PK: #FF9CC8;
    --dark-PK:  #332F31;
    --text1-PK: #341D2C;
    --text1m-PK:#341D2C;
    --up-PK:    #A562E9;
    --down-PK:  #628FE9;
    --test-PK:  red;
}

/* mixins */
.rounded() {
    border-radius: 4px;
}

/* post entry */
.entry {
    .rounded();
    border-top: 20px solid var(--pink2-PK);
    border-right: 5px solid var(--pink2-PK);
    border-bottom: 5px solid var(--pink2-PK);
    border-left: 5px solid var(--pink2-PK);
    
    .vote button {
        border-right: 3px solid var(--pink2-PK);
        border-bottom: 3px solid var(--pink2-PK);
        .rounded();
    }
}
```

![image](https://github.com/openstyles/stylus/assets/137783738/cc89b51e-06e7-4868-9b17-2108cea2c1af)
