### DISCUSSION TITLE
Same Style in Every `@preprocessor` (stylus, less, uso, default)

### DISCUSSION THREAD

**Discussion by pabli24** [openstyles/stylus#1717] [General]
### Make sure to enable UserCSS editor
![usercss editor](https://github.com/user-attachments/assets/affd00c8-891f-4ac6-bb01-84b5fd4db810)

## Config example ⚙️
![stylus example config](https://github.com/user-attachments/assets/d245b529-efa2-4815-97dd-3aee83d66dd6)

# `@preprocessor stylus` - [stylus-lang.com](https://stylus-lang.com/)

```stylus
/* ==UserStyle==
@name         example.com STYLUS
@version      1.0.0
@namespace    example STYLUS
@license      WTFPL
@preprocessor stylus
@var          select   fonts  "Font"          ["Roboto", "Helvetica", "'Comic Sans MS'"]
@var          color    txt    "Text"          #fff
@var          color    link   "Link"          #7790ff
@var          color    bg     "Background"    #000
@var          checkbox bgImg  "Image"         1 
@var          text     bgImgL "Image Link"    "'https://cataas.com/cat?width=1000'"
@var          number   divW   "Width"         [600, 200, null, 1, "px"]
@var          range    divBr  "Border radius" [15, 5, 50, 1, "px"]
==/UserStyle== */
@-moz-document domain("example.com")
	body
		background-color bg
		if bgImg
			background-image url(bgImgL)
		color txt
		font-family fonts
	div
		background-color lighten(bg, 5%)
		width divW
		border-radius divBr
	a:link, a:visited
		color link
```
or
```stylus
/* ==UserStyle==
@name         example.com STYLUS
@version      1.0.0
@namespace    example STYLUS
@license      WTFPL
@preprocessor stylus
@var          select   fonts  "Font"          ["Roboto", "Helvetica", "'Comic Sans MS'"]
@var          color    txt    "Text"          #fff
@var          color    link   "Link"          #7790ff
@var          color    bg     "Background"    #000
@var          checkbox bgImg  "Image"         1 
@var          text     bgImgL "Image Link"    "'https://cataas.com/cat?width=1000'"
@var          number   divW   "Width"         [600, 200, null, 1, "px"]
@var          range    divBr  "Border radius" [15, 5, 50, 1, "px"]
==/UserStyle== */
@-moz-document domain("example.com") {
	body {
		background-color: bg;
		if bgImg {
			background-image: url(bgImgL);
		}
		color: txt;
		font-family: fonts;
	}
	div {
		background-color: lighten(bg, 5%);
		width: divW;
		border-radius: divBr;
	}
	a:link, a:visited {
		color: link;
	}
}
```

<details><summary><b>Output (click to expand)</b></summary>

UserCSS `@var` Metadata → Stylus Preprocessor

```stylus
fonts = Roboto
txt = #fff
link = #7790ff
bg = #000
bgImg = 1
bgImgL = 'https://cataas.com/cat?width=1000'
divW = 600px
divBr = 15px
@-moz-document domain("example.com") {
	body {
		background-color: bg;
		if bgImg {
			background-image: url(bgImgL);
		}
		color: txt;
		font-family: fonts;
	}
	div {
		background-color: lighten(bg, 5%);
		width: divW;
		border-radius: divBr;
	}
	a:link, a:visited {
		color: link;
	}
}
```

Stylus Preprocessor → CSS

```stylus
@-moz-document domain("example.com") {
	body {
		background-color: #000;
		background-image: url("https://cataas.com/cat?width=1000");
		color: #fff;
		font-family: Roboto;
	}
	div {
		background-color: #0d0d0d;
		width: 600px;
		border-radius: 15px;
	}
	a:link,
	a:visited {
		color: #7790ff;
	}
}
```

CSS → Injecting style at the bottom of the DOM on websites specified in the `@-moz-document` rule

```css
<style id="stylus-420" type="text/css" class="stylus" data-name="example.com STYLUS">
body {
	background-color: #000;
	background-image: url("https://cataas.com/cat?width=1000");
	color: #fff;
	font-family: Roboto;
}
div {
	background-color: #0d0d0d;
	width: 600px;
	border-radius: 15px;
}
a:link,
a:visited {
	color: #7790ff;
}
/*# sourceURL=chrome-extension://apmmpaebfobifelkijhaljbmpcgbjbdo/example.com.user.css#420 */</style>
</html>
```

</details>
<br>

# `@preprocessor less` - [lesscss.org](https://lesscss.org/)

```less
/* ==UserStyle==
@name         example.com LESS
@version      1.0.0
@namespace    example LESS
@license      WTFPL
@preprocessor less
@var          select   fonts  "Font"          ["Roboto", "Helvetica", "'Comic Sans MS'"]
@var          color    txt    "Text"          #fff
@var          color    link   "Link"          #7790ff
@var          color    bg     "Background"    #000
@var          checkbox bgImg  "Image"         1 
@var          text     bgImgL "Image Link"    "'https://cataas.com/cat?width=1000'"
@var          number   divW   "Width"         [600, 200, null, 1, "px"]
@var          range    divBr  "Border radius" [15, 5, 30, 1, "px"]
==/UserStyle== */
@-moz-document domain("example.com") {
	body {
		background-color: @bg;
		& when (@bgImg = 1) {
			background-image: url(@bgImgL);
		}
		color: @txt;
		font-family: @fonts;
	}
	div {
		background-color: lighten(@bg, 5%);
		width: @divW;
		border-radius: @divBr;
	}
	a:link, a:visited {
		color: @link;
	}
}
```

<details><summary><b>Output (click to expand)</b></summary>

UserCSS `@var` Metadata → Less Preprocessor
```less
@fonts: Roboto;
@txt: #fff;
@link: #7790ff;
@bg: #000;
@bgImg: 1;
@bgImgL: 'https://cataas.com/cat?width=1000';
@divW: 600px;
@divBr: 15px;
@-moz-document domain("example.com") {
	body {
		background-color: @bg;
		& when (@bgImg = 1) {
			background-image: url(@bgImgL);
		}
		color: @txt;
		font-family: @fonts;
	}
	div {
		background-color: lighten(@bg, 5%);
		width: @divW;
		border-radius: @divBr;
	}
	a:link, a:visited {
		color: @link;
	}
}
```

Less Preprocessor → CSS

```stylus
@-moz-document domain("example.com") {
	body {
		background-color: #000;
		background-image: url('https://cataas.com/cat?width=1000');
		color: #fff;
		font-family: Roboto;
	}
	div {
		background-color: #0d0d0d;
		width: 600px;
		border-radius: 15px;
	}
	a:link,
	a:visited {
		color: #7790ff;
	}
}
```

CSS → Injecting style at the bottom of the DOM on websites specified in the `@-moz-document` rule

```css
<style id="stylus-420" type="text/css" class="stylus" data-name="example.com LESS">
body {
	background-color: #000;
	background-image: url('https://cataas.com/cat?width=1000');
	color: #fff;
	font-family: Roboto;
}
div {
	background-color: #0d0d0d;
	width: 600px;
	border-radius: 15px;
}
a:link,
a:visited {
	color: #7790ff;
}
/*# sourceURL=chrome-extension://apmmpaebfobifelkijhaljbmpcgbjbdo/example.com.user.css#420 */</style>
</html>
```

</details>
<br>

# `@preprocessor uso` - [userstyles.org docs](https://userstyles.org/help/coding) ([Archive](https://web.archive.org/web/20130911063113/http://userstyles.org/help/coding#help-style-settings))

```css
/* ==UserStyle==
@name         example.com USO
@version      1.0.0
@namespace    example USO
@license      WTFPL
@preprocessor uso
@var          select   fonts  "Font"          ["Roboto", "Helvetica", "'Comic Sans MS'"]
@var          color    txt    "Text"          #fff
@var          color    link   "Link"          #7790ff
@var          color    bg     "Background"    #000
@var          select   bgImg  "Image" {
	"ON": "background-image: url(/*[[bgImgL]]*\/);",
	"OFF": ""
}
@var          text     bgImgL "Image Link"    "https://cataas.com/cat?width=1000"
@var          number   divW   "Width"         [600, 200, null, 1, "px"]
@var          range    divBr  "Border radius" [15, 5, 30, 1, "px"]
==/UserStyle== */
@-moz-document domain("example.com") {
	body {
		background-color: /*[[bg]]*/;
		/*[[bgImg]]*/
		color: /*[[txt]]*/;
		font-family: /*[[fonts]]*/;
	}
	div {
		background-color: color-mix(in srgb, /*[[bg]]*/, #fff 5%);
		width: /*[[divW]]*/;
		border-radius: /*[[divBr]]*/;
	}
	a:link, a:visited {
		color: /*[[link]]*/;
	}
}
```

<details><summary><b>Output (click to expand)</b></summary>

UserCSS `@var` Metadata → USO Preprocessor → CSS

```css
@-moz-document domain("example.com") {
	body {
		background-color: #000000;
		background-image: url('https://cataas.com/cat?width=1000');
		color: #ffffff;
		font-family: Roboto;
	}
	div {
		background-color: color-mix(in srgb, #000000, #fff 5%);
		width: 600px;
		border-radius: 15px;
	}
	a:link, a:visited {
		color: #7790ff;
	}
}
```

CSS → Injecting style at the bottom of the DOM on websites specified in the `@-moz-document` rule

```css
<style id="stylus-420" type="text/css" class="stylus" data-name="example.com USO">
body {
	background-color: #000000;
	background-image: url(https://cataas.com/cat?width=1000);
	color: #ffffff;
	font-family: Roboto;
}
div {
	background-color: color-mix(in srgb, #000000, #fff 5%);
	width: 600px;
	border-radius: 15px;
}
a:link, a:visited {
	color: #7790ff;
}
/*# sourceURL=chrome-extension://apmmpaebfobifelkijhaljbmpcgbjbdo/example.com.user.css#420 */</style>
</html>
```

</details>
<br>

<details><summary><b>Working "@var checkbox" (if statement) in the uso preprocessor (click to expand)</b></summary>

`@supports (grid-area: 1) {}` - ON
`@supports (grid-area: 0) {}` - OFF (invalid property value)

```css
/* ==UserStyle==
@name         example.com USO
@version      1.0.0
@namespace    example USO
@license      WTFPL
@preprocessor uso
@var          select   fonts  "Font"          ["Roboto", "Helvetica", "'Comic Sans MS'"]
@var          color    txt    "Text"          #fff
@var          color    link   "Link"          #7790ff
@var          color    bg     "Background"    #000
@var          checkbox bgImg  "Image"         1
@var          text     bgImgL "Image Link"    "https://cataas.com/cat?width=1000"
@var          number   divW   "Width"         [600, 200, null, 1, "px"]
@var          range    divBr  "Border radius" [15, 5, 30, 1, "px"]
==/UserStyle== */
@-moz-document domain("example.com") {
	body {
		background-color: /*[[bg]]*/;
		color: /*[[txt]]*/;
		font-family: /*[[fonts]]*/;
	}
	@supports (grid-area: /*[[bgImg]]*/) {
		body {
			background-image: url(/*[[bgImgL]]*/);
		}
	}
	div {
		background-color: color-mix(in srgb, /*[[bg]]*/, #fff 5%);
		width: /*[[divW]]*/;
		border-radius: /*[[divBr]]*/;
	}
	a:link, a:visited {
		color: /*[[link]]*/;
	}
}
```

</details>
<br>

# `@preprocessor default` - [CSS Variables](https://developer.mozilla.org/docs/Web/CSS/Using_CSS_variables)

```css
/* ==UserStyle==
@name         example.com DEFAULT
@version      1.0.0
@namespace    example DEFAULT
@license      WTFPL
@preprocessor default
@var          select   fonts  "Font"          ["Roboto", "Helvetica", "'Comic Sans MS'"]
@var          color    txt    "Text"          #fff
@var          color    link   "Link"          #7790ff
@var          color    bg     "Background"    #000
@var          select   bgImg  "Image" {
	"ON": "var(--bgImgL, none)",
	"OFF": "none"
}
@var          text     bgImgL "Image Link"    "url(https://cataas.com/cat?width=1000)"
@var          number   divW   "Width"         [600, 200, null, 1, "px"]
@var          range    divBr  "Border radius" [15, 5, 30, 1, "px"]
==/UserStyle== */
@-moz-document domain("example.com") {
	body {
		background-color: var(--bg);
		background-image: var(--bgImg);
		color: var(--txt);
		font-family: var(--fonts);
	}
	div {
		background-color: color-mix(in srgb, var(--bg), #fff 5%);
		width: var(--divW);
		border-radius: var(--divBr);
	}
	a:link, a:visited {
		color: var(--link);
	}
}
```

<details><summary><b>Output (click to expand)</b></summary>

UserCSS `@var` Metadata → Default Preprocessor → CSS

```css
@-moz-document domain("example.com") {
	:root {
		--fonts: Roboto;
		--txt: #fff;
		--link: #7790ff;
		--bg: #000;
		--bgImg: var(--bgImgL, none);
		--bgImgL: url(https://cataas.com/cat?width=1000);
		--divW: 600px;
		--divBr: 15px;
	}
	body {
		background-color: var(--bg);
		background-image: var(--bgImg);
		color: var(--txt);
		font-family: var(--fonts);
	}
	div {
		background-color: color-mix(in srgb, var(--bg), #fff 5%);
		width: var(--divW);
		border-radius: var(--divBr);
	}
	a:link, a:visited {
		color: var(--link);
	}
}
```

CSS → Injecting style at the bottom of the DOM on websites specified in the `@-moz-document` rule

```css
<style id="stylus-420" type="text/css" class="stylus" data-name="example.com DEFAULT">
:root {
	--fonts: Roboto;
	--txt: #fff;
	--link: #7790ff;
	--bg: #000;
	--bgImg: var(--bgImgL, none);
	--bgImgL: url(https://cataas.com/cat?width=1000);
	--divW: 600px;
	--divBr: 15px;
}
body {
	background-color: var(--bg);
	background-image: var(--bgImg);
	color: var(--txt);
	font-family: var(--fonts);
}
div {
	background-color: color-mix(in srgb, var(--bg), #fff 5%);
	width: var(--divW);
	border-radius: var(--divBr);
}
a:link, a:visited {
	color: var(--link);
}
/*# sourceURL=chrome-extension://apmmpaebfobifelkijhaljbmpcgbjbdo/example.com.user.css#420 */</style>
</html>
```

</details>
<br>

<details><summary><b>Working "@var checkbox" (if statement) in the default preprocessor (click to expand)</b></summary>

https://caniuse.com/mdn-css_at-rules_container_style_queries_for_custom_properties
Firefox: `about:config` → `layout.css.style-queries.enabled` `true`

```css
/* ==UserStyle==
@name         example.com DEFAULT
@version      1.0.0
@namespace    example DEFAULT
@license      WTFPL
@preprocessor default
@var          select   fonts  "Font"          ["Roboto", "Helvetica", "'Comic Sans MS'"]
@var          color    txt    "Text"          #fff
@var          color    link   "Link"          #7790ff
@var          color    bg     "Background"    #000
@var          checkbox bgImg  "Image"         1
@var          text     bgImgL "Image Link"    "url(https://cataas.com/cat?width=1000)"
@var          number   divW   "Width"         [600, 200, null, 1, "px"]
@var          range    divBr  "Border radius" [15, 5, 30, 1, "px"]
==/UserStyle== */
@-moz-document domain("example.com") {
	body {
		background-color: var(--bg);
		color: var(--txt);
		font-family: var(--fonts);
	}
	@container style(--bgImg: 1) {
		body {
			background-image: var(--bgImgL, none);
		}
	}
	div {
		background-color: color-mix(in srgb, var(--bg), #fff 5%);
		width: var(--divW);
		border-radius: var(--divBr);
	}
	a:link, a:visited {
		color: var(--link);
	}
}
```
```css
/* ==UserStyle==
@name         example.com Rounded Corners
@version      1.0.0
@namespace    example DEFAULT
@license      WTFPL
@preprocessor default
@var          checkbox br "Rounded Corners" 1
==/UserStyle== */
@-moz-document domain("example.com") {
	div {
		--br-1: 30px;
		--br-0: 0px;
		border-radius: calc(var(--br) * var(--br-1) + (1 - var(--br)) * var(--br-0));
	}
}
```
</details>
