### DISCUSSION TITLE
some elements not picked up in Firefox

### DISCUSSION THREAD

**Discussion by toppits** [openstyles/stylus#1748] [Q&A] [answered]
For example:
body#stylus-manage .entry .actions{display: none !important}

Doesn't work in FF, while working fine in chrome. What am i missing

**Comment by tophf** [comment, marked as answer]
Works for me in FF.
I guess there's a mistake in your `@-moz-document` (applies-to).

```css
@-moz-document regexp("^\\w+-extension://[^/]+/manage.*") {
body#stylus-manage .entry .actions{display: none !important}
}
```
