### DISCUSSION TITLE
Style Injected to Jira Servicedesk Gets Overwritten

### DISCUSSION THREAD

**Discussion by thekief** [openstyles/stylus#1811] [Q&A] [answered]
I wanted to make a small custom style for Jira Servicedesk so more than a mere third of the screen is used to display the issue. To do so, I created this very small snippet:

```css
#content-wrapper {
    width: 80%;
}
```

When loading a page I can see that for a brief moment the width modification is applied. Once the site finished loading, it returns to the default width. 

Is there a workaround to ensure that the stylesheet applied by Stylus is not overwritten by stylesheets that are loaded later on?

**Comment by tophf** [comment, marked as answer]
Increase the specificity by adding `!important`:
```css
#content-wrapper { width: 80% !important }
```
and optionally by adding dummy ids:
```css
#content-wrapper:not(#foo) { width: 80% !important }
```

More info: https://github.com/openstyles/stylus/wiki/Writing-styles#overwriting-page-styles
